"""API schemas for the ChillValve backend."""
from __future__ import annotations

from typing import Dict, List, Literal, Optional

from pydantic import BaseModel

Mode = Literal["belimo", "chillvalve"]
EngineStatus = Literal["idle", "running", "paused"]


class HealthResponse(BaseModel):
    status: str = "ok"
    engine: EngineStatus
    scenario: Optional[str] = None
    mode: Optional[Mode] = None
    tick: int = 0


class StartResponse(BaseModel):
    status: Literal["started"]
    scenario: str
    mode: Mode
    tick: int


class StatusResponse(BaseModel):
    engine: EngineStatus
    tick: int
    scenario: Optional[str] = None
    mode: Optional[Mode] = None


class HistoryRow(BaseModel):
    timestamp_s: float
    valve_id: str
    branch_id: str
    flow_gpm: Optional[float]
    dT_C: Optional[float]
    position_pct: Optional[float]
    dP_kPa: Optional[float]
    mode: Optional[str]


class HistoryResponse(BaseModel):
    since_s: float
    rows: List[HistoryRow]


class ValveSnapshot(BaseModel):
    valve_id: str
    branch_id: str
    flow_gpm: float
    dT_C: float
    position_pct: float
    is_leader: bool
    anomaly_detected: bool
    anomaly_confidence: float
    rule_fired: Optional[str]
    safety_override_active: bool


class WSStateMessage(BaseModel):
    type: Literal["state"] = "state"
    tick: int
    pump_kw: float
    pump_head_kpa: float
    total_flow_gpm: float
    valves: List[ValveSnapshot]


class WSExplanationMessage(BaseModel):
    """Operator-facing narration for significant events.
    Generated by an LLM out-of-band; not part of the control loop."""
    type: Literal["explanation"] = "explanation"
    kind: Literal["leader"]
    branch_id: str
    previous_leader: Optional[str]
    new_leader: str
    cause: str
    tick: int
    text: str


class DebateSpeech(BaseModel):
    valve_id: str
    # Structured fields — peer reports its state in machine-readable form so
    # leader + UI don't parse prose.
    status: Optional[Literal["impaired", "nominal"]] = None
    flow_pct: Optional[int] = None
    request: Optional[
        Literal["open_more", "hold", "take_load", "close_more"]
    ] = None
    reason: Optional[str] = None
    # Legacy free-text kept optional for backward compat.
    text: Optional[str] = None


class WSDebateMessage(BaseModel):
    """Multi-agent LLM debate transcript. Replaces deterministic Layer 3
    setpoints for a branch when Layer 2's confidence is in the uncertain
    band. Layer 1 still validates the resulting commands."""
    type: Literal["debate"] = "debate"
    branch_id: str
    tick: int
    leader_id: str
    speeches: List[DebateSpeech]
    allocations: Dict[str, float]
    rationale: str
    cached: bool
    wall_clock_s: float


class WSRemediationMessage(BaseModel):
    """Autonomous Layer-3 recovery decision. Emitted after a sustained
    anomaly that peer-reallocation did not resolve. The elected branch
    leader picks one of three actions; the engine executes any whose effect
    is in-band of the simulator (currently: attempt_actuator_reset)."""
    type: Literal["remediation"] = "remediation"
    branch_id: str
    target_valve_id: str
    leader_id: str
    tick: int
    action: Literal[
        "attempt_actuator_reset", "schedule_maintenance", "accept_degradation"
    ]
    rationale: str
    executed: bool
    text: str
    wall_clock_s: float


class WSSummaryMessage(BaseModel):
    """End-of-run energy summary. Emitted once when the scenario reaches
    duration_seconds (not on external stop). Quotes MEASURED per-phase
    pump_kW so the dashboard can show real recovery savings instead of any
    contrived steady-state vs Belimo claim. Phases:
      pre_fault: from t=0 until first anomaly_detected anywhere
      during_fault: anomaly active, no executed reset yet
      post_recovery: after L3 executed attempt_actuator_reset and anomaly cleared
    recovery_savings_kw = max(0, mean_kw_during_fault - mean_kw_post_recovery)."""
    type: Literal["summary"] = "summary"
    scenario: str
    duration_s: int
    total_kwh: float
    mean_kw_pre_fault: float
    mean_kw_during_fault: float
    mean_kw_post_recovery: float
    recovery_fired: bool
    recovery_savings_kw: float
    recovery_savings_kwh: float
    dt_compliance_pct: float
